server:
  port : 8081
spring:
  profiles:
    active: local
  application:
    name: "hello-word"
greeting-service:
  url: http://localhost:8082
  path:
    get-mapping: /api/get-mapping
    path-variable: /api/path-variable/{user_id}
    request-param: /api/request-param
    request-body: /api/request-body
